[package]
name = "identifier_forest"
version = "0.1.0"
authors = ["Julian Bruyat <bruyat.ju@live.fr>", "Pierre-Antoine Champin <pierre-antoine.champin@ercim.eu>"]
edition = "2018"

[dependencies]
once_cell = "1.3.1"
